/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;


import vistasdeladmin.Manejok;
import vistasdeladmin.manejodepartamentos;
import vistasdeladmin.manejoregiones;
import vistasdeladmin.reportes;

/**
 *
 * @author juanj
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Administrador() {
        initComponents();
                     this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanejok = new javax.swing.JButton();
        btnmanejor = new javax.swing.JButton();
        btnmaenejod = new javax.swing.JButton();
        btnreporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnmanejok.setText("Manejo de kioscos");
        btnmanejok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanejokActionPerformed(evt);
            }
        });

        btnmanejor.setText("Manejo de regiones y precios");
        btnmanejor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanejorActionPerformed(evt);
            }
        });

        btnmaenejod.setText("Manejo de departamentos y municipios");
        btnmaenejod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmaenejodActionPerformed(evt);
            }
        });

        btnreporte.setText("Reportes");
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmanejok, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmanejor, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmaenejod)
                    .addComponent(btnreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnmanejok)
                .addGap(56, 56, 56)
                .addComponent(btnmanejor)
                .addGap(60, 60, 60)
                .addComponent(btnmaenejod)
                .addGap(47, 47, 47)
                .addComponent(btnreporte)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanejokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanejokActionPerformed
        Manejok frame = new Manejok();
        frame.setVisible(true);    }//GEN-LAST:event_btnmanejokActionPerformed

    private void btnmanejorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanejorActionPerformed
        manejoregiones frame = new manejoregiones();
        frame.setVisible(true);     }//GEN-LAST:event_btnmanejorActionPerformed

    private void btnmaenejodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaenejodActionPerformed
        manejodepartamentos frame = new manejodepartamentos();
        frame.setVisible(true);
    }//GEN-LAST:event_btnmaenejodActionPerformed

    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
    reportes frame = new reportes();
        frame.setVisible(true);    }//GEN-LAST:event_btnreporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
                
                          
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmaenejod;
    private javax.swing.JButton btnmanejok;
    private javax.swing.JButton btnmanejor;
    private javax.swing.JButton btnreporte;
    // End of variables declaration//GEN-END:variables
}
