/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasdeladmin;


import static admin.beans.Admins.listaKioscos;
import java.awt.Frame;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.beans.Usuarios;
import regionesyprecios.Region;
import regionesyprecios.Regiones;
import static regionesyprecios.Regiones.regiones;
import static regionesyprecios.Regiones.regiones;



/**
 *
 * @author juanj
 */
public class manejodepartamentos extends javax.swing.JFrame {

    /**
     * Creates new form manejoD
     * @param parent
     * @param modal
     */
    public manejodepartamentos() {
          
        initComponents();
             this.setLocationRelativeTo(null);
                 

            
        for (Region region : regiones) {
        codigoregionm.addItem(region.getCodigoregion());
                }


        for (Region region : regiones) {
        codigoregionm.addItem(region.getCodigoregion());
                }

          

                
             
               
                
            
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btnagregardepartamento = new javax.swing.JButton();
        codigoregionm = new javax.swing.JComboBox<>();
        regionesc = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        departamentoComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Manejo de departamentos y municipios ");

        jLabel2.setText("Datos del departamento ");

        jLabel3.setText("Codigo de region ");

        jLabel4.setText("Region:");

        jLabel5.setText("Nombre departamento");

        jLabel6.setText("Datos de Municipio ");

        jLabel7.setText("Código de departamento ");

        jLabel8.setText("Nombre ");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        btnagregardepartamento.setText("AGREGAR DEPARTAMENTO  ");
        btnagregardepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregardepartamentoActionPerformed(evt);
            }
        });

        codigoregionm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoregionmActionPerformed(evt);
            }
        });

        regionesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionescActionPerformed(evt);
            }
        });

        jButton1.setText("agregar municipio ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        departamentoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoComboBoxActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnagregardepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(codigoregionm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(regionesc, 0, 150, Short.MAX_VALUE))
                                .addGap(347, 347, 347)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel1))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addComponent(codigoregionm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regionesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregardepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
   
    
        
    private void codigoregionmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoregionmActionPerformed
 String codigo = (String) codigoregionm.getSelectedItem();
    ArrayList<Region> regiones = Regiones.getRegiones();

    regionesc.removeAllItems();
    regionesc.addItem(null);
    for (Region region : regiones) {
        if (region.getCodigoregion().equals(codigo)) {
            regionesc.addItem(region.getNombreRegion()); 
        }
    }
        
   

    }//GEN-LAST:event_codigoregionmActionPerformed

    
    
    
    
    
    
    private void regionescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionescActionPerformed
String codigo = (String) codigoregionm.getSelectedItem();
    ArrayList<Region> regiones = Regiones.getRegiones();

    
    departamentoComboBox.removeAllItems();
    departamentoComboBox.addItem(null);
    for (Region region : regiones) {
        if (region.getCodigoregion().equals(codigo)) {
            departamentoComboBox.addItem(region.getDepartamento()); 
        }

    
}

    }//GEN-LAST:event_regionescActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            String codigo = departamentoComboBox.getSelectedItem().toString();
                String region = regionesc.getSelectedItem().toString();
                String nombre = jTextField3.getText();

        int index = -1;
        for (int i = 0; i < regiones.size(); i++) {
         if (regiones.get(i).getDepartamento().equals(codigo)) {
             index = i;
        break;
    }
    }

        if (index != -1) {
    String nuevomuni = jTextField4.getText();
    Region regionActual = regiones.get(index);
    regionActual.setMunicipio(nuevomuni);
    regiones.set(index, regionActual);
    
    JOptionPane.showMessageDialog(null, "Municipio agregado correctamente al departamento " + codigo);

    
    
}












    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnagregardepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregardepartamentoActionPerformed

        
                String codigo = codigoregionm.getSelectedItem().toString();
                String region = regionesc.getSelectedItem().toString();
                String nombre = jTextField3.getText();

        int index = -1;
        for (int i = 0; i < regiones.size(); i++) {
         if (regiones.get(i).getCodigoregion().equals(codigo)) {
             index = i;
        break;
    }
    }

        if (index != -1) {
    String nuevodep = jTextField3.getText();
    Region regionActual = regiones.get(index);
    regionActual.setDepartamento(nuevodep);
    regiones.set(index, regionActual);
    
    
}
             
        
        
        
        
// Obtener la región seleccionada del JComboBox de regiones
int indiceSeleccionado = regionesc.getSelectedIndex();
Region regionSeleccionada = regiones.get(indiceSeleccionado);

// Obtener el texto ingresado en el JTextField
String departamentoIngresado = jTextField3.getText();

// Agregar el departamento ingresado a la región seleccionada
regionSeleccionada.setDepartamento(departamentoIngresado);

// Actualizar la lista de regiones en la clase Regiones
int indice = regionesc.getSelectedIndex();
Regiones.editarRegion(indice, regionSeleccionada.getNombreRegion(), regionSeleccionada.getPrecioEstandar(), regionSeleccionada.getPrecioEspecial());

// Agregar el departamento al ComboBox de departamentos
DefaultComboBoxModel departamentoModel = (DefaultComboBoxModel) departamentoComboBox.getModel();
departamentoModel.addElement(departamentoIngresado);

// Obtener el nombre de la región seleccionada del ComboBox de regiones
String nombreRegionSeleccionada = (String) regionesc.getSelectedItem();

// Mostrar un mensaje de éxito con el nombre de la región seleccionada
JOptionPane.showMessageDialog(null, "Departamento agregado correctamente a la región " + nombreRegionSeleccionada);
    }//GEN-LAST:event_btnagregardepartamentoActionPerformed

    private void departamentoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String codigo = (String) codigoregionm.getSelectedItem();
    ArrayList<Region> regiones = Regiones.getRegiones();

    
    // Actualizar combobox de departamentos
    departamentoComboBox.removeAllItems();
    departamentoComboBox.addItem(null);
    for (Region region : regiones) {
        if (region.getCodigoregion().equals(codigo)) {
            departamentoComboBox.addItem(region.getDepartamento()); 
        }
    }    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manejodepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manejodepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manejodepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manejodepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manejodepartamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregardepartamento;
    private javax.swing.JComboBox<String> codigoregionm;
    private javax.swing.JComboBox<String> departamentoComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> regionesc;
    // End of variables declaration//GEN-END:variables
}
